version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
