# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:10-alpine as build-stage
RUN apk add --no-cache bash
WORKDIR /app
COPY ./client/package*.json /app/
RUN yarn install
COPY ./client/ /app/
COPY ./server/src/schema/schema.graphql /app/schema/
RUN npm run build
