version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: npm run start
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
    tty: true
    stdin_open: true
    ports:
      - 3000:8080
