# Stage 0, "build-stage", based on Node.js, to build and compile the frontend
FROM node:10-alpine as build-stage
RUN apk add --no-cache bash
WORKDIR /app
COPY package*.json /app/
RUN yarn install
COPY ./ /app/
RUN npm run build
